-- =============================================================
-- PARTNERBET PRO V2 — CONSOLIDATED SUPABASE SCHEMA
-- Auto-generated by concatenating supabase/migrations/*.sql in order.
-- Copy this WHOLE file into Supabase SQL Editor and click Run —
-- one shot, no coding required. (Developers: use the individual
-- files in supabase/migrations/ with the Supabase CLI instead.)
-- =============================================================

-- ///////////////////////////////////////////////////////////
-- FILE: migrations/0001_extensions_and_helpers.sql
-- ///////////////////////////////////////////////////////////
-- =========================================================
-- 0001 — EXTENSIONS & GENERIC HELPERS
-- =========================================================
create extension if not exists pgcrypto;   -- gen_random_uuid()
create extension if not exists pg_trgm;    -- fast ILIKE / fuzzy search on text (search feature, Phase 5)

-- Generic trigger: keeps updated_at current on every UPDATE.
-- Applied to every table below that has an updated_at column.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ///////////////////////////////////////////////////////////
-- FILE: migrations/0002_roles_permissions.sql
-- ///////////////////////////////////////////////////////////
-- =========================================================
-- 0002 — ROLES & PERMISSIONS (normalized RBAC)
-- Seed data here is structural (role/permission definitions), not content.
-- =========================================================
create table roles (
  id uuid primary key default gen_random_uuid(),
  key text not null unique,              -- 'super_admin' | 'admin' | 'editor' | 'user'
  name text not null,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger trg_roles_updated_at before update on roles
  for each row execute function public.set_updated_at();

create table permissions (
  id uuid primary key default gen_random_uuid(),
  key text not null unique,              -- e.g. 'posts.manage'
  description text,
  created_at timestamptz not null default now()
);

create table role_permissions (
  role_id uuid not null references roles(id) on delete cascade,
  permission_id uuid not null references permissions(id) on delete cascade,
  primary key (role_id, permission_id)
);
create index idx_role_permissions_permission on role_permissions(permission_id);

-- ---------- Seed: base roles ----------
insert into roles (key, name, description) values
  ('super_admin', 'Super Admin', 'Full control: content, settings, users, roles, logs'),
  ('admin',       'Admin',       'Full content & settings control, cannot manage roles/permissions'),
  ('editor',      'Editor',      'Can create and edit content only, no settings/users/ads access'),
  ('user',        'User',        'Base authenticated visitor account (future public features)');

-- ---------- Seed: permission catalogue ----------
insert into permissions (key, description) values
  ('posts.manage',           'Create, edit, delete, publish blog posts'),
  ('football_news.manage',   'Create, edit, delete, publish football news'),
  ('match_insights.manage',  'Create, edit, delete match insights'),
  ('promotions.manage',      'Manage promo codes'),
  ('apk.manage',             'Manage APK releases'),
  ('advertisements.manage',  'Manage banners / ads / embeds'),
  ('media.manage',           'Upload / delete media library files'),
  ('taxonomy.manage',        'Manage categories & tags'),
  ('faqs.manage',            'Manage FAQ entries'),
  ('navigation.manage',      'Manage header/footer navigation'),
  ('settings.manage',        'Manage site-wide settings (SEO, theme, contact, social, hero)'),
  ('support.manage',         'View and respond to support conversations'),
  ('users.manage',           'View and change roles of other users'),
  ('roles.manage',           'Create/edit roles and permission assignments'),
  ('logs.view',              'View audit logs');

-- ---------- Seed: role -> permission mapping ----------
-- super_admin: every permission
insert into role_permissions (role_id, permission_id)
select (select id from roles where key = 'super_admin'), id from permissions;

-- admin: everything except roles.manage
insert into role_permissions (role_id, permission_id)
select (select id from roles where key = 'admin'), id
from permissions where key <> 'roles.manage';

-- editor: content-creation permissions only
insert into role_permissions (role_id, permission_id)
select (select id from roles where key = 'editor'), id
from permissions
where key in ('posts.manage', 'football_news.manage', 'match_insights.manage', 'media.manage');

-- user: no admin permissions (intentionally none inserted)

-- ///////////////////////////////////////////////////////////
-- FILE: migrations/0003_profiles.sql
-- ///////////////////////////////////////////////////////////
-- =========================================================
-- 0003 — PROFILES (1:1 extension of auth.users)
-- Replaces the old "admin_profiles" table with a unified profile
-- for every authenticated user (admins today, public users in Phase 2+).
-- =========================================================
create table profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role_id uuid not null references roles(id),
  full_name text,
  avatar_url text,
  is_active boolean not null default true,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index idx_profiles_role_id on profiles(role_id);

create trigger trg_profiles_updated_at before update on profiles
  for each row execute function public.set_updated_at();

-- Auto-create a base "user" profile whenever a new Supabase auth account is
-- created. Admin roles are never self-assigned — an existing super_admin
-- must promote the account afterwards (see README / DB docs).
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, role_id, full_name)
  values (
    new.id,
    (select id from public.roles where key = 'user'),
    new.raw_user_meta_data ->> 'full_name'
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ///////////////////////////////////////////////////////////
-- FILE: migrations/0004_rbac_functions_and_core_rls.sql
-- ///////////////////////////////////////////////////////////
-- =========================================================
-- 0004 — RBAC HELPER FUNCTIONS + RLS FOR ROLES/PERMISSIONS/PROFILES
-- =========================================================

-- Returns true if the currently authenticated user's role has the given
-- permission key. Used in every RLS policy below instead of repeating
-- role-lookup joins everywhere.
create or replace function public.has_permission(perm_key text)
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from profiles p
    join role_permissions rp on rp.role_id = p.role_id
    join permissions perm on perm.id = rp.permission_id
    where p.id = auth.uid()
      and p.is_active = true
      and perm.key = perm_key
  );
$$;

-- Returns true if the user has ANY admin-level permission at all — used to
-- gate "can this account even open /admin" checks (middleware, layout).
create or replace function public.is_admin_user()
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from profiles p
    join role_permissions rp on rp.role_id = p.role_id
    where p.id = auth.uid()
      and p.is_active = true
  );
$$;

-- ---------- RLS: roles / permissions / role_permissions ----------
-- NOTE: the SELECT policies below are superseded by migration 0020
-- (tightened from "any authenticated user" to "admin accounts only").
-- Kept here unmodified so migration history stays accurate/replayable.
alter table roles enable row level security;
alter table permissions enable row level security;
alter table role_permissions enable row level security;

create policy "authenticated read roles" on roles
  for select using (auth.role() = 'authenticated');
create policy "roles.manage write roles" on roles
  for all using (has_permission('roles.manage')) with check (has_permission('roles.manage'));

create policy "authenticated read permissions" on permissions
  for select using (auth.role() = 'authenticated');
create policy "roles.manage write permissions" on permissions
  for all using (has_permission('roles.manage')) with check (has_permission('roles.manage'));

create policy "authenticated read role_permissions" on role_permissions
  for select using (auth.role() = 'authenticated');
create policy "roles.manage write role_permissions" on role_permissions
  for all using (has_permission('roles.manage')) with check (has_permission('roles.manage'));

-- ---------- RLS: profiles ----------
alter table profiles enable row level security;

-- Everyone can read + update their own profile row.
create policy "self read profile" on profiles
  for select using (id = auth.uid());
create policy "self update profile" on profiles
  for update using (id = auth.uid())
  with check (id = auth.uid());

-- Guard against self-elevation: if the person making the change does NOT
-- hold users.manage, silently keep their role_id unchanged no matter what
-- value they submitted. (A trigger is used instead of an RLS check because
-- RLS CHECK clauses cannot reliably compare NEW vs OLD on the same row.)
create or replace function public.prevent_self_role_escalation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.id = auth.uid() and not has_permission('users.manage') then
    new.role_id := old.role_id;
  end if;
  return new;
end;
$$;

create trigger trg_prevent_self_role_escalation
  before update on profiles
  for each row execute function public.prevent_self_role_escalation();

-- users.manage holders can read & update anyone's profile (e.g. to change roles).
create policy "users.manage read all profiles" on profiles
  for select using (has_permission('users.manage'));
create policy "users.manage update all profiles" on profiles
  for update using (has_permission('users.manage'))
  with check (has_permission('users.manage'));

-- ///////////////////////////////////////////////////////////
-- FILE: migrations/0005_audit_logs.sql
-- ///////////////////////////////////////////////////////////
-- =========================================================
-- 0005 — AUDIT LOGS
-- Automatic, tamper-resistant change history for every sensitive table.
-- Rows are written by a SECURITY DEFINER trigger, never by the app
-- directly — no role (not even admins) gets INSERT/UPDATE/DELETE on
-- this table, only logs.view holders may read it.
-- =========================================================
create table audit_logs (
  id uuid primary key default gen_random_uuid(),
  actor_id uuid references profiles(id) on delete set null,
  action text not null check (action in ('INSERT', 'UPDATE', 'DELETE')),
  table_name text not null,
  record_id uuid,
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz not null default now()
);

-- BRIN index: ideal for large, append-only, time-ordered tables (millions
-- of rows) — far smaller and faster to maintain here than a btree.
create index idx_audit_logs_created_at_brin on audit_logs using brin (created_at);
create index idx_audit_logs_table_record on audit_logs (table_name, record_id);
create index idx_audit_logs_actor on audit_logs (actor_id);

create or replace function public.audit_trigger()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if (tg_op = 'DELETE') then
    insert into audit_logs (actor_id, action, table_name, record_id, old_data)
    values (auth.uid(), 'DELETE', tg_table_name, old.id, to_jsonb(old));
    return old;
  elsif (tg_op = 'UPDATE') then
    insert into audit_logs (actor_id, action, table_name, record_id, old_data, new_data)
    values (auth.uid(), 'UPDATE', tg_table_name, new.id, to_jsonb(old), to_jsonb(new));
    return new;
  elsif (tg_op = 'INSERT') then
    insert into audit_logs (actor_id, action, table_name, record_id, new_data)
    values (auth.uid(), 'INSERT', tg_table_name, new.id, to_jsonb(new));
    return new;
  end if;
  return null;
end;
$$;

alter table audit_logs enable row level security;
create policy "logs.view read audit_logs" on audit_logs
  for select using (has_permission('logs.view'));
-- Intentionally no insert/update/delete policy for any role: only the
-- SECURITY DEFINER trigger function can write here.

-- ///////////////////////////////////////////////////////////
-- FILE: migrations/0006_media.sql
-- ///////////////////////////////////////////////////////////
-- =========================================================
-- 0006 — MEDIA LIBRARY
-- Metadata for files stored in the "media" and "apk" Supabase Storage
-- buckets (created in migration 0019). Referenced by posts, football
-- news, advertisements, etc. via foreign keys instead of raw URLs.
-- =========================================================
create table media (
  id uuid primary key default gen_random_uuid(),
  file_name text not null,
  storage_path text not null,        -- path inside the Supabase Storage bucket
  public_url text not null,
  mime_type text not null,
  file_size_bytes bigint,
  width int,
  height int,
  alt_text text,
  uploaded_by uuid references profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);
create index idx_media_uploaded_by on media(uploaded_by);
create index idx_media_not_deleted on media(created_at desc) where deleted_at is null;

alter table media enable row level security;

-- Public read: image URLs must load on the public website without login.
create policy "public read media" on media
  for select using (deleted_at is null);

create policy "media.manage full access" on media
  for all using (has_permission('media.manage')) with check (has_permission('media.manage'));

create trigger trg_audit_media
  after insert or update or delete on media
  for each row execute function public.audit_trigger();

-- ///////////////////////////////////////////////////////////
-- FILE: migrations/0007_taxonomy.sql
-- ///////////////////////////////////////////////////////////
-- =========================================================
-- 0007 — TAXONOMY: categories (per content type, nestable) & tags (global)
-- =========================================================
create table categories (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null,
  content_type text not null check (content_type in ('post', 'football_news')),
  parent_id uuid references categories(id) on delete set null,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  unique (slug, content_type)
);
create index idx_categories_content_type on categories(content_type) where deleted_at is null;
create index idx_categories_parent on categories(parent_id);

create trigger trg_categories_updated_at before update on categories
  for each row execute function public.set_updated_at();
create trigger trg_audit_categories
  after insert or update or delete on categories
  for each row execute function public.audit_trigger();

alter table categories enable row level security;
create policy "public read categories" on categories
  for select using (deleted_at is null);
create policy "taxonomy.manage full access categories" on categories
  for all using (has_permission('taxonomy.manage')) with check (has_permission('taxonomy.manage'));

create table tags (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  slug text not null unique,
  created_at timestamptz not null default now()
);

alter table tags enable row level security;
create policy "public read tags" on tags for select using (true);
create policy "taxonomy.manage full access tags" on tags
  for all using (has_permission('taxonomy.manage')) with check (has_permission('taxonomy.manage'));

-- ///////////////////////////////////////////////////////////
-- FILE: migrations/0008_posts.sql
-- ///////////////////////////////////////////////////////////
-- =========================================================
-- 0008 — POSTS (blog / SEO articles). Replaces "blog_posts".
-- =========================================================
create table posts (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  slug text not null unique,
  excerpt text,
  content text not null,
  cover_media_id uuid references media(id) on delete set null,
  category_id uuid references categories(id) on delete set null,
  author_id uuid references profiles(id) on delete set null,
  status text not null default 'draft' check (status in ('draft', 'scheduled', 'published', 'archived')),
  language text not null default 'en' check (language in ('en', 'ru', 'uz')),
  seo_title text,
  seo_description text,
  seo_keywords text[],
  view_count bigint not null default 0,
  published_at timestamptz,
  scheduled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);
-- Pagination / listing queries always filter by status + order by published_at.
create index idx_posts_status_published on posts(status, published_at desc) where deleted_at is null;
create index idx_posts_category on posts(category_id);
create index idx_posts_author on posts(author_id);
create index idx_posts_slug on posts(slug) where deleted_at is null;
create index idx_posts_title_trgm on posts using gin (title gin_trgm_ops); -- fast search (Phase 5)

create trigger trg_posts_updated_at before update on posts
  for each row execute function public.set_updated_at();
create trigger trg_audit_posts
  after insert or update or delete on posts
  for each row execute function public.audit_trigger();

alter table posts enable row level security;
create policy "public read published posts" on posts
  for select using (status = 'published' and deleted_at is null and (published_at is null or published_at <= now()));
create policy "posts.manage full access" on posts
  for all using (has_permission('posts.manage')) with check (has_permission('posts.manage'));

create table post_tags (
  post_id uuid not null references posts(id) on delete cascade,
  tag_id uuid not null references tags(id) on delete cascade,
  primary key (post_id, tag_id)
);
create index idx_post_tags_tag on post_tags(tag_id);

alter table post_tags enable row level security;
create policy "public read post_tags" on post_tags for select using (true);
create policy "posts.manage full access post_tags" on post_tags
  for all using (has_permission('posts.manage')) with check (has_permission('posts.manage'));

-- ///////////////////////////////////////////////////////////
-- FILE: migrations/0009_football_news.sql
-- ///////////////////////////////////////////////////////////
-- =========================================================
-- 0009 — FOOTBALL NEWS (distinct from generic posts: league-tagged)
-- =========================================================
create table football_news (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  slug text not null unique,
  excerpt text,
  content text not null,
  cover_media_id uuid references media(id) on delete set null,
  category_id uuid references categories(id) on delete set null,
  league text,
  author_id uuid references profiles(id) on delete set null,
  status text not null default 'draft' check (status in ('draft', 'scheduled', 'published', 'archived')),
  seo_title text,
  seo_description text,
  view_count bigint not null default 0,
  published_at timestamptz,
  scheduled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);
create index idx_football_news_status_published on football_news(status, published_at desc) where deleted_at is null;
create index idx_football_news_league on football_news(league);
create index idx_football_news_category on football_news(category_id);

create trigger trg_football_news_updated_at before update on football_news
  for each row execute function public.set_updated_at();
create trigger trg_audit_football_news
  after insert or update or delete on football_news
  for each row execute function public.audit_trigger();

alter table football_news enable row level security;
create policy "public read published football_news" on football_news
  for select using (status = 'published' and deleted_at is null and (published_at is null or published_at <= now()));
create policy "football_news.manage full access" on football_news
  for all using (has_permission('football_news.manage')) with check (has_permission('football_news.manage'));

-- ///////////////////////////////////////////////////////////
-- FILE: migrations/0010_match_insights.sql
-- ///////////////////////////////////////////////////////////
-- =========================================================
-- 0010 — MATCH INSIGHTS. Replaces "insights" (same columns app already
-- uses, now with soft delete, updated_by, and profiles FK instead of
-- admin_profiles).
-- =========================================================
create table match_insights (
  id uuid primary key default gen_random_uuid(),
  league text not null,
  home_team text not null,
  away_team text not null,
  match_time timestamptz not null,
  expected_goals text,
  possession_trend text,
  confidence smallint check (confidence between 0 and 100),
  analysis text,
  status text not null default 'UPCOMING'
    check (status in ('UPCOMING', 'LIVE', 'WIN', 'LOST', 'PUSH', 'POSTPONED', 'CANCELLED')),
  created_by uuid references profiles(id) on delete set null,
  updated_by uuid references profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);
create index idx_match_insights_match_time on match_insights(match_time) where deleted_at is null;
create index idx_match_insights_status on match_insights(status);
create index idx_match_insights_league on match_insights(league);

create trigger trg_match_insights_updated_at before update on match_insights
  for each row execute function public.set_updated_at();
create trigger trg_audit_match_insights
  after insert or update or delete on match_insights
  for each row execute function public.audit_trigger();

alter table match_insights enable row level security;
create policy "public read match_insights" on match_insights
  for select using (deleted_at is null);
create policy "match_insights.manage full access" on match_insights
  for all using (has_permission('match_insights.manage')) with check (has_permission('match_insights.manage'));

-- ///////////////////////////////////////////////////////////
-- FILE: migrations/0011_promotions.sql
-- ///////////////////////////////////////////////////////////
-- =========================================================
-- 0011 — PROMOTIONS (replaces hardcoded PROMOS array in the frontend)
-- =========================================================
create table promotions (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  title text not null,
  description text,
  terms text,
  partner_name text,
  cta_url text,
  is_active boolean not null default true,
  valid_from timestamptz,
  valid_until timestamptz,
  click_count bigint not null default 0,
  created_by uuid references profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);
create index idx_promotions_active on promotions(is_active) where deleted_at is null;

create trigger trg_promotions_updated_at before update on promotions
  for each row execute function public.set_updated_at();
create trigger trg_audit_promotions
  after insert or update or delete on promotions
  for each row execute function public.audit_trigger();

alter table promotions enable row level security;
create policy "public read active promotions" on promotions
  for select using (is_active = true and deleted_at is null
    and (valid_from is null or valid_from <= now())
    and (valid_until is null or valid_until >= now()));
create policy "promotions.manage full access" on promotions
  for all using (has_permission('promotions.manage')) with check (has_permission('promotions.manage'));

-- ///////////////////////////////////////////////////////////
-- FILE: migrations/0012_apk_releases.sql
-- ///////////////////////////////////////////////////////////
-- =========================================================
-- 0012 — APK RELEASES (same shape the app already uses + extra columns)
-- =========================================================
create table apk_releases (
  id uuid primary key default gen_random_uuid(),
  version text not null,
  download_url text not null,
  file_size_bytes bigint,
  checksum_sha256 text,
  changelog text,
  min_android text default '8.0',
  is_active boolean not null default false,
  downloads_count bigint not null default 0,
  created_by uuid references profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);
-- DB-enforced invariant: at most one active release at a time
-- (previously only enforced by app-code doing 2 sequential updates).
create unique index idx_apk_releases_one_active
  on apk_releases (is_active)
  where is_active = true and deleted_at is null;

create index idx_apk_releases_created_at on apk_releases(created_at desc) where deleted_at is null;

create trigger trg_apk_releases_updated_at before update on apk_releases
  for each row execute function public.set_updated_at();
create trigger trg_audit_apk_releases
  after insert or update or delete on apk_releases
  for each row execute function public.audit_trigger();

alter table apk_releases enable row level security;
create policy "public read active apk" on apk_releases
  for select using (is_active = true and deleted_at is null);
create policy "apk.manage full access" on apk_releases
  for all using (has_permission('apk.manage')) with check (has_permission('apk.manage'));

-- ///////////////////////////////////////////////////////////
-- FILE: migrations/0013_advertisements.sql
-- ///////////////////////////////////////////////////////////
-- =========================================================
-- 0013 — ADVERTISEMENTS (unifies old "ads" + planned "banners" into one
-- table via a `kind` discriminator — avoids two near-identical tables).
-- =========================================================
create table advertisements (
  id uuid primary key default gen_random_uuid(),
  kind text not null check (kind in ('image', 'embed', 'banner')),
  placement text not null check (placement in (
    'homepage', 'blog', 'insights', 'football_news', 'apk_page',
    'popup', 'sticky', 'sidebar', 'footer', 'header'
  )),
  title text,
  image_media_id uuid references media(id) on delete set null,
  image_url text,        -- fallback for direct URL entry before Media Library (Phase 4) is wired up
  embed_code text,
  target_url text,
  position int not null default 0,
  is_active boolean not null default true,
  starts_at timestamptz,
  ends_at timestamptz,
  clicks bigint not null default 0,
  views bigint not null default 0,
  created_by uuid references profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);
create index idx_advertisements_placement_active
  on advertisements(placement, is_active) where deleted_at is null;

create trigger trg_advertisements_updated_at before update on advertisements
  for each row execute function public.set_updated_at();
create trigger trg_audit_advertisements
  after insert or update or delete on advertisements
  for each row execute function public.audit_trigger();

alter table advertisements enable row level security;
create policy "public read active advertisements" on advertisements
  for select using (is_active = true and deleted_at is null
    and (starts_at is null or starts_at <= now())
    and (ends_at is null or ends_at >= now()));
create policy "advertisements.manage full access" on advertisements
  for all using (has_permission('advertisements.manage')) with check (has_permission('advertisements.manage'));

-- ///////////////////////////////////////////////////////////
-- FILE: migrations/0014_site_settings.sql
-- ///////////////////////////////////////////////////////////
-- =========================================================
-- 0014 — SITE SETTINGS (generic key/value JSONB store)
-- Powers the "website builder" admin sections (Homepage, Header, Footer,
-- Hero, Theme, SEO defaults, Analytics, Contact, Social links) WITHOUT a
-- separate table per section — each is one JSONB row, editable from the
-- dashboard, extensible without new migrations for new fields inside it.
-- =========================================================
create table site_settings (
  id uuid primary key default gen_random_uuid(),
  key text not null unique,
  value jsonb not null default '{}'::jsonb,
  updated_by uuid references profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger trg_site_settings_updated_at before update on site_settings
  for each row execute function public.set_updated_at();
create trigger trg_audit_site_settings
  after insert or update or delete on site_settings
  for each row execute function public.audit_trigger();

alter table site_settings enable row level security;
-- Public read: the frontend needs these values (site name, hero copy,
-- contact email, social links, SEO defaults, theme) to render pages.
create policy "public read site_settings" on site_settings
  for select using (true);
create policy "settings.manage full access" on site_settings
  for all using (has_permission('settings.manage')) with check (has_permission('settings.manage'));

-- ---------- Seed: structural rows only (empty/neutral defaults, no fake content) ----------
insert into site_settings (key, value) values
  ('site_identity', '{"site_name": "PartnerBet", "tagline": "", "logo_media_id": null}'),
  ('hero_section', '{"headline": "", "subheadline": "", "cta_label": "", "cta_url": ""}'),
  ('contact_info', '{"email": "", "phone": "", "address": ""}'),
  ('social_links', '{"facebook": "", "instagram": "", "telegram": "", "twitter": ""}'),
  ('seo_defaults', '{"default_title": "", "default_description": "", "og_image_media_id": null}'),
  ('analytics', '{"ga_measurement_id": "", "meta_pixel_id": ""}'),
  ('theme', '{"mode": "dark", "accent_color": "#00A3FF"}');

-- ///////////////////////////////////////////////////////////
-- FILE: migrations/0015_navigation.sql
-- ///////////////////////////////////////////////////////////
-- =========================================================
-- 0015 — NAVIGATION (header/footer menu items, admin-orderable tree)
-- =========================================================
create table navigation_items (
  id uuid primary key default gen_random_uuid(),
  label text not null,
  url text not null,
  location text not null check (location in ('header', 'footer')),
  parent_id uuid references navigation_items(id) on delete cascade,
  position int not null default 0,
  is_active boolean not null default true,
  opens_new_tab boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);
create index idx_navigation_location_position on navigation_items(location, position) where deleted_at is null;

create trigger trg_navigation_items_updated_at before update on navigation_items
  for each row execute function public.set_updated_at();
create trigger trg_audit_navigation_items
  after insert or update or delete on navigation_items
  for each row execute function public.audit_trigger();

alter table navigation_items enable row level security;
create policy "public read active navigation" on navigation_items
  for select using (is_active = true and deleted_at is null);
create policy "navigation.manage full access" on navigation_items
  for all using (has_permission('navigation.manage')) with check (has_permission('navigation.manage'));

-- ///////////////////////////////////////////////////////////
-- FILE: migrations/0016_faqs.sql
-- ///////////////////////////////////////////////////////////
-- =========================================================
-- 0016 — FAQ
-- =========================================================
create table faqs (
  id uuid primary key default gen_random_uuid(),
  question text not null,
  answer text not null,
  category text,
  position int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);
create index idx_faqs_position on faqs(position) where deleted_at is null;

create trigger trg_faqs_updated_at before update on faqs
  for each row execute function public.set_updated_at();
create trigger trg_audit_faqs
  after insert or update or delete on faqs
  for each row execute function public.audit_trigger();

alter table faqs enable row level security;
create policy "public read active faqs" on faqs
  for select using (is_active = true and deleted_at is null);
create policy "faqs.manage full access" on faqs
  for all using (has_permission('faqs.manage')) with check (has_permission('faqs.manage'));

-- ///////////////////////////////////////////////////////////
-- FILE: migrations/0017_support.sql
-- ///////////////////////////////////////////////////////////
-- =========================================================
-- 0017 — SUPPORT CHAT (kept from the original skeleton, hardened;
-- backend wiring happens in Phase 4).
-- =========================================================
create table support_conversations (
  id uuid primary key default gen_random_uuid(),
  visitor_name text not null,
  visitor_email text not null,
  status text not null default 'open' check (status in ('open', 'resolved')),
  assigned_admin_id uuid references profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index idx_support_conversations_status on support_conversations(status);

create trigger trg_support_conversations_updated_at before update on support_conversations
  for each row execute function public.set_updated_at();

create table support_messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references support_conversations(id) on delete cascade,
  sender text not null check (sender in ('visitor', 'admin')),
  message text not null,
  created_at timestamptz not null default now()
);
create index idx_support_messages_conversation on support_messages(conversation_id, created_at);

alter table support_conversations enable row level security;
alter table support_messages enable row level security;

-- Visitors can create a conversation + send messages (no login required for
-- support chat), but cannot read other people's conversations — the app
-- will scope reads through a server-side API route using the service-role
-- key rather than exposing conversations directly to anon SELECT.
create policy "anon insert conversation" on support_conversations
  for insert with check (true);
create policy "support.manage full access conversations" on support_conversations
  for all using (has_permission('support.manage')) with check (has_permission('support.manage'));

create policy "anon insert message" on support_messages
  for insert with check (true);
create policy "support.manage full access messages" on support_messages
  for all using (has_permission('support.manage')) with check (has_permission('support.manage'));

-- ///////////////////////////////////////////////////////////
-- FILE: migrations/0018_analytics_events.sql
-- ///////////////////////////////////////////////////////////
-- =========================================================
-- 0018 — ANALYTICS EVENTS (high-volume, append-only, time-series)
-- BRIN index instead of btree on created_at: this table is expected to
-- reach millions of rows, and BRIN stays tiny + fast for time-ordered inserts.
-- =========================================================
create table analytics_events (
  id uuid primary key default gen_random_uuid(),
  event_type text not null,     -- page_view, apk_download, promo_copy, register_click, ad_click
  country text,
  language text,
  device text,
  meta jsonb,
  created_at timestamptz not null default now()
);
create index idx_analytics_events_type on analytics_events(event_type);
create index idx_analytics_events_created_at_brin on analytics_events using brin (created_at);

alter table analytics_events enable row level security;
create policy "public insert analytics" on analytics_events
  for insert with check (true);
create policy "logs.view read analytics" on analytics_events
  for select using (has_permission('logs.view'));

-- ///////////////////////////////////////////////////////////
-- FILE: migrations/0019_storage_buckets.sql
-- ///////////////////////////////////////////////////////////
-- =========================================================
-- 0019 — STORAGE BUCKETS
-- =========================================================
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('media', 'media', true, 20971520, array['image/png','image/jpeg','image/webp','image/svg+xml','video/mp4']),
  ('apk',   'apk',   true, 209715200, array['application/vnd.android.package-archive'])
on conflict (id) do nothing;

-- Public read for both buckets (images/APK must load without auth).
create policy "public read media bucket" on storage.objects
  for select using (bucket_id = 'media');
create policy "public read apk bucket" on storage.objects
  for select using (bucket_id = 'apk');

-- Uploads/deletes require the matching manage permission.
create policy "media.manage upload media bucket" on storage.objects
  for insert with check (bucket_id = 'media' and has_permission('media.manage'));
create policy "media.manage update media bucket" on storage.objects
  for update using (bucket_id = 'media' and has_permission('media.manage'));
create policy "media.manage delete media bucket" on storage.objects
  for delete using (bucket_id = 'media' and has_permission('media.manage'));

create policy "apk.manage upload apk bucket" on storage.objects
  for insert with check (bucket_id = 'apk' and has_permission('apk.manage'));
create policy "apk.manage update apk bucket" on storage.objects
  for update using (bucket_id = 'apk' and has_permission('apk.manage'));
create policy "apk.manage delete apk bucket" on storage.objects
  for delete using (bucket_id = 'apk' and has_permission('apk.manage'));

-- ///////////////////////////////////////////////////////////
-- FILE: migrations/0020_phase1_hardening.sql
-- ///////////////////////////////////////////////////////////
-- =========================================================
-- 0020 — PHASE 1 VERIFICATION FIXES
-- Found during the Phase 1 verification pass (see DATABASE_TEST_REPORT.md
-- and SECURITY_REPORT.md). Applied as a new migration rather than editing
-- migration history, per standard practice.
-- =========================================================

-- ---------------------------------------------------------------
-- FIX 1 — audit_trigger() requires a NEW/OLD.id column. profiles, roles
-- and permissions all have one, but were missing the trigger entirely —
-- meaning role changes and permission-catalogue edits were NOT being
-- logged. These are the most security-sensitive tables in the whole
-- schema, so this was a real gap.
-- ---------------------------------------------------------------
create trigger trg_audit_profiles
  after insert or update or delete on profiles
  for each row execute function public.audit_trigger();

create trigger trg_audit_roles
  after insert or update or delete on roles
  for each row execute function public.audit_trigger();

create trigger trg_audit_permissions
  after insert or update or delete on permissions
  for each row execute function public.audit_trigger();

-- ---------------------------------------------------------------
-- FIX 2 — role_permissions has a composite primary key (role_id,
-- permission_id), not an `id` column, so the generic audit_trigger()
-- would fail at runtime ("record new has no field id") if attached
-- directly. A dedicated composite-key variant is used instead so that
-- privilege-grant changes (e.g. removing roles.manage from admin) are
-- still fully audited.
-- ---------------------------------------------------------------
create or replace function public.audit_trigger_composite_key()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if (tg_op = 'DELETE') then
    insert into audit_logs (actor_id, action, table_name, old_data)
    values (auth.uid(), 'DELETE', tg_table_name, to_jsonb(old));
    return old;
  elsif (tg_op = 'INSERT') then
    insert into audit_logs (actor_id, action, table_name, new_data)
    values (auth.uid(), 'INSERT', tg_table_name, to_jsonb(new));
    return new;
  end if;
  return null;
end;
$$;

create trigger trg_audit_role_permissions
  after insert or delete on role_permissions
  for each row execute function public.audit_trigger_composite_key();

-- ---------------------------------------------------------------
-- FIX 3 — roles / permissions / role_permissions were readable by ANY
-- authenticated account (auth.role() = 'authenticated'). Phase 2 will
-- introduce plain public "user" accounts, which should NOT be able to
-- read the internal permission/role structure. Tightened to
-- is_admin_user() (true only for accounts whose role actually grants at
-- least one admin permission).
-- ---------------------------------------------------------------
drop policy "authenticated read roles" on roles;
create policy "admins read roles" on roles
  for select using (is_admin_user());

drop policy "authenticated read permissions" on permissions;
create policy "admins read permissions" on permissions
  for select using (is_admin_user());

drop policy "authenticated read role_permissions" on role_permissions;
create policy "admins read role_permissions" on role_permissions
  for select using (is_admin_user());

-- ---------------------------------------------------------------
-- FIX 4 — post_tags was readable by literally anyone with no check that
-- the associated post is actually published. This let an outside caller
-- discover tag associations (post_id + tag_id pairs) for DRAFT/unpublished
-- posts by querying the table directly, bypassing the posts table's own
-- "published only" public policy (low-severity info leak, but a real gap).
-- ---------------------------------------------------------------
drop policy "public read post_tags" on post_tags;
create policy "public read post_tags of published posts" on post_tags
  for select using (
    exists (
      select 1 from posts p
      where p.id = post_tags.post_id
        and p.status = 'published'
        and p.deleted_at is null
    )
  );

-- ---------------------------------------------------------------
-- FIX 5 — support_conversations / support_messages allowed an anonymous
-- visitor to INSERT with check(true), meaning anyone could set
-- status = 'resolved', assign an arbitrary assigned_admin_id, or — most
-- seriously — insert a message with sender = 'admin' into ANY conversation
-- id, spoofing a fake admin reply. Insert policies are now scoped to only
-- the fields a real visitor should be able to set.
-- ---------------------------------------------------------------
drop policy "anon insert conversation" on support_conversations;
create policy "anon insert open conversation" on support_conversations
  for insert with check (status = 'open' and assigned_admin_id is null);

drop policy "anon insert message" on support_messages;
create policy "anon insert visitor message" on support_messages
  for insert with check (sender = 'visitor');

-- ///////////////////////////////////////////////////////////
-- FILE: migrations/0021_phase2_roles_expansion.sql
-- ///////////////////////////////////////////////////////////
-- =========================================================
-- 0021 — PHASE 2: EXPAND ROLES TO FULL 8-ROLE MATRIX
-- Adds: moderator, support, affiliate_manager, content_manager
-- (super_admin, admin, editor, user already exist from 0002).
-- =========================================================
insert into roles (key, name, description) values
  ('moderator',         'Moderator',         'Moderates match insights, FAQs and support conversations'),
  ('support',           'Support',           'Handles support conversations only'),
  ('affiliate_manager', 'Affiliate Manager', 'Manages promotions, advertisements and APK releases'),
  ('content_manager',   'Content Manager',   'Senior content role: posts, football news, match insights, media, taxonomy, FAQs, navigation');

-- content_manager: broader content oversight than editor (adds taxonomy, faqs, navigation)
insert into role_permissions (role_id, permission_id)
select (select id from roles where key = 'content_manager'), id
from permissions
where key in (
  'posts.manage', 'football_news.manage', 'match_insights.manage',
  'media.manage', 'taxonomy.manage', 'faqs.manage', 'navigation.manage'
);

-- moderator: content moderation + support triage
insert into role_permissions (role_id, permission_id)
select (select id from roles where key = 'moderator'), id
from permissions
where key in ('support.manage', 'match_insights.manage', 'faqs.manage');

-- support: support conversations only
insert into role_permissions (role_id, permission_id)
select (select id from roles where key = 'support'), id
from permissions
where key = 'support.manage';

-- affiliate_manager: monetization-adjacent modules
insert into role_permissions (role_id, permission_id)
select (select id from roles where key = 'affiliate_manager'), id
from permissions
where key in ('promotions.manage', 'advertisements.manage', 'apk.manage');

-- ///////////////////////////////////////////////////////////
-- FILE: migrations/0022_login_attempts.sql
-- ///////////////////////////////////////////////////////////
-- =========================================================
-- 0022 — LOGIN ATTEMPTS (brute-force protection / rate limiting)
-- Written exclusively by the server (service-role client) from the
-- /api/auth/login route — no RLS policy grants anon/authenticated
-- access at all, so this table is invisible to every normal client.
-- =========================================================
create table login_attempts (
  id uuid primary key default gen_random_uuid(),
  identifier text not null,     -- lowercased email being attempted
  ip_address text,
  user_agent text,
  success boolean not null,
  created_at timestamptz not null default now()
);
create index idx_login_attempts_identifier on login_attempts(identifier, created_at desc);
create index idx_login_attempts_ip on login_attempts(ip_address, created_at desc);
create index idx_login_attempts_created_at_brin on login_attempts using brin (created_at);

alter table login_attempts enable row level security;
-- Intentionally NO policies at all: only the service-role key (which
-- bypasses RLS entirely) may read/write this table.

-- ///////////////////////////////////////////////////////////
-- FILE: migrations/0023_profiles_locale.sql
-- ///////////////////////////////////////////////////////////
-- =========================================================
-- 0023 — PROFILE LOCALE (per-user UI language preference)
-- =========================================================
alter table profiles
  add column locale text not null default 'uz' check (locale in ('uz', 'ru', 'en'));

-- ///////////////////////////////////////////////////////////
-- FILE: migrations/0024_site_settings_phase3.sql
-- ///////////////////////////////////////////////////////////
-- =========================================================
-- 0024 — PHASE 3a: SITE SETTINGS EXPANSION + SECURE API CREDENTIALS
-- =========================================================

-- ---------- New site_settings keys (public, non-secret config) ----------
insert into site_settings (key, value) values
  ('footer', '{"description": "", "footer_text": ""}'),
  ('maintenance', '{"enabled": false, "message": ""}'),
  ('branding', '{"logo_media_id": null, "favicon_media_id": null}')
on conflict (key) do nothing;

-- Expand the existing "theme" row with the extra colour fields Phase 3
-- needs (site already has "theme" from 0014 with mode+accent_color).
update site_settings
set value = value || '{"secondary_color": "#FFC857", "background_color": "#07111F"}'::jsonb
where key = 'theme'
  and not (value ? 'secondary_color');

-- =========================================================
-- SECURE API CREDENTIALS
-- Stores secrets that must NEVER be exposed to the browser (football API
-- key, push notification server keys). Unlike site_settings, this table
-- has NO RLS policies at all for anon/authenticated — only the
-- service-role key (used exclusively from server-only API routes) can
-- read or write it. The admin UI never receives the actual secret value
-- back, only a "configured / not configured" status.
-- =========================================================
create table api_credentials (
  id uuid primary key default gen_random_uuid(),
  key text not null unique,   -- e.g. 'football_api_key', 'push_fcm_server_key'
  value text not null,
  is_active boolean not null default true,
  updated_by uuid references profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger trg_api_credentials_updated_at before update on api_credentials
  for each row execute function public.set_updated_at();
create trigger trg_audit_api_credentials
  after insert or update or delete on api_credentials
  for each row execute function public.audit_trigger();

alter table api_credentials enable row level security;
-- Intentionally NO policies: only the service-role client can touch this
-- table, from server-only route handlers, after that route independently
-- verifies the caller holds settings.manage via has_permission().

-- ///////////////////////////////////////////////////////////
-- FILE: migrations/0025_affiliate_manager.sql
-- ///////////////////////////////////////////////////////////
-- =========================================================
-- 0025 — PHASE 3b: ENTERPRISE AFFILIATE MANAGER
-- Supersedes the simple Phase 1 "promotions" table (one row = one flat
-- promo code) with a proper Partner ↔ Promo Codes ↔ Redirect Rules ↔
-- Clicks model. Architecture supports unlimited affiliate companies —
-- nothing about any specific brand is hardcoded anywhere in this schema.
-- =========================================================

-- The old flat table is fully replaced by affiliate_partners + promo_codes
-- below; dropping it (cascade removes its indexes/triggers/policies) keeps
-- the schema free of two overlapping "promotion" concepts.
drop table if exists promotions cascade;

-- ---------------------------------------------------------------
-- AFFILIATE PARTNERS
-- ---------------------------------------------------------------
create table affiliate_partners (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,                  -- used in /go/{slug} redirect links
  name text not null check (char_length(name) between 1 and 200),
  logo_media_id uuid references media(id) on delete set null,
  logo_url text,   -- denormalized cache of media.public_url, avoids a join on every public read
  description text check (description is null or char_length(description) <= 2000),

  website_url text check (website_url is null or website_url ~ '^https?://'),
  affiliate_url text not null check (affiliate_url ~ '^https?://'),
  apk_url text check (apk_url is null or apk_url ~ '^https?://'),
  google_play_url text check (google_play_url is null or google_play_url ~ '^https?://'),
  app_store_url text check (app_store_url is null or app_store_url ~ '^https?://'),
  deep_link text check (deep_link is null or deep_link ~ '^[a-zA-Z][a-zA-Z0-9+.-]*://'),

  bonus_description text check (bonus_description is null or char_length(bonus_description) <= 1000),
  countries text[],           -- ISO 3166-1 alpha-2 codes; null/empty = all countries
  languages text[],           -- e.g. {uz,ru,en}; null/empty = all languages
  rating numeric(2,1) check (rating is null or (rating >= 0 and rating <= 5)),
  priority int not null default 0,   -- lower = shown first
  is_active boolean not null default true,
  is_featured boolean not null default false,

  -- Link Health (populated by /api/admin/affiliates/check-links and the
  -- scheduled /api/cron/check-affiliate-links job — see AFFILIATE_MANAGER.md)
  link_health jsonb not null default '{}'::jsonb,
  link_health_checked_at timestamptz,

  click_count bigint not null default 0,   -- fast denormalized counter; affiliate_clicks is the source of truth

  created_by uuid references profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);
create index idx_affiliate_partners_active on affiliate_partners(priority) where deleted_at is null and is_active = true;
create index idx_affiliate_partners_slug on affiliate_partners(slug) where deleted_at is null;
create index idx_affiliate_partners_featured on affiliate_partners(is_featured) where deleted_at is null and is_active = true;

create trigger trg_affiliate_partners_updated_at before update on affiliate_partners
  for each row execute function public.set_updated_at();
create trigger trg_audit_affiliate_partners
  after insert or update or delete on affiliate_partners
  for each row execute function public.audit_trigger();

alter table affiliate_partners enable row level security;
create policy "public read active partners" on affiliate_partners
  for select using (is_active = true and deleted_at is null);
create policy "promotions.manage full access partners" on affiliate_partners
  for all using (has_permission('promotions.manage')) with check (has_permission('promotions.manage'));

-- ---------------------------------------------------------------
-- PROMO CODES (a partner can have many)
-- ---------------------------------------------------------------
create table promo_codes (
  id uuid primary key default gen_random_uuid(),
  partner_id uuid not null references affiliate_partners(id) on delete cascade,
  code text not null check (char_length(code) between 1 and 50),
  bonus_description text check (bonus_description is null or char_length(bonus_description) <= 500),
  is_featured boolean not null default false,
  is_active boolean not null default true,
  expires_at timestamptz,
  usage_count bigint not null default 0,
  created_by uuid references profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  unique (partner_id, code)
);
create index idx_promo_codes_partner on promo_codes(partner_id) where deleted_at is null;
create index idx_promo_codes_active on promo_codes(is_active) where deleted_at is null;

create trigger trg_promo_codes_updated_at before update on promo_codes
  for each row execute function public.set_updated_at();
create trigger trg_audit_promo_codes
  after insert or update or delete on promo_codes
  for each row execute function public.audit_trigger();

alter table promo_codes enable row level security;
create policy "public read active promo_codes" on promo_codes
  for select using (
    is_active = true and deleted_at is null and (expires_at is null or expires_at >= now())
  );
create policy "promotions.manage full access promo_codes" on promo_codes
  for all using (has_permission('promotions.manage')) with check (has_permission('promotions.manage'));

-- ---------------------------------------------------------------
-- SMART REDIRECT RULES (per-partner overrides by country/language/device)
-- Not publicly readable — only the server-side /go/{slug} route (via the
-- service-role client) and admins can see targeting logic.
-- ---------------------------------------------------------------
create table partner_redirect_rules (
  id uuid primary key default gen_random_uuid(),
  partner_id uuid not null references affiliate_partners(id) on delete cascade,
  match_type text not null check (match_type in ('country', 'language', 'device')),
  match_value text not null,   -- e.g. 'UZ', 'ru', 'mobile'
  target_url text not null check (target_url ~ '^https?://'),
  priority int not null default 0,   -- lower = evaluated first
  is_active boolean not null default true,
  created_by uuid references profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index idx_redirect_rules_partner on partner_redirect_rules(partner_id, priority);

create trigger trg_redirect_rules_updated_at before update on partner_redirect_rules
  for each row execute function public.set_updated_at();
create trigger trg_audit_redirect_rules
  after insert or update or delete on partner_redirect_rules
  for each row execute function public.audit_trigger();

alter table partner_redirect_rules enable row level security;
create policy "promotions.manage full access redirect_rules" on partner_redirect_rules
  for all using (has_permission('promotions.manage')) with check (has_permission('promotions.manage'));
-- Intentionally no public policy — the /go route reads this via the
-- service-role client (server-only, not exposed to the browser).

-- ---------------------------------------------------------------
-- CLICK ANALYTICS (high-volume, append-only, time-series)
-- Written exclusively by /go/{slug} via the service-role client.
-- ---------------------------------------------------------------
create table affiliate_clicks (
  id uuid primary key default gen_random_uuid(),
  partner_id uuid references affiliate_partners(id) on delete set null,
  banner_id uuid references advertisements(id) on delete set null,
  target_url text not null,
  country text,
  device text check (device in ('desktop', 'mobile', 'tablet', 'unknown')),
  browser text,
  language text,
  referrer text,
  created_at timestamptz not null default now()
);
create index idx_affiliate_clicks_partner on affiliate_clicks(partner_id, created_at desc);
create index idx_affiliate_clicks_created_at_brin on affiliate_clicks using brin (created_at);
create index idx_affiliate_clicks_country on affiliate_clicks(country);
create index idx_affiliate_clicks_device on affiliate_clicks(device);

alter table affiliate_clicks enable row level security;
create policy "promotions.manage read affiliate_clicks" on affiliate_clicks
  for select using (has_permission('promotions.manage'));
-- No insert/update/delete policy for anyone — only the service-role
-- client (from /go/{slug}) writes here.

-- ---------------------------------------------------------------
-- BANNER MANAGER: extend the existing advertisements table (Phase 1)
-- rather than creating a second, overlapping "banners" table.
-- ---------------------------------------------------------------
alter table advertisements
  add column partner_id uuid references affiliate_partners(id) on delete set null,
  add column banner_size text check (banner_size in ('desktop', 'tablet', 'mobile', 'square', 'popup', 'sticky', 'hero')),
  add column target_countries text[],   -- null/empty = all countries
  add column target_languages text[],   -- null/empty = all languages
  add column width_px int,
  add column height_px int;

-- Retroactive URL validation (Phase 1 shipped these columns without a
-- format check) — added now as part of the Phase 3b security requirement
-- to validate every URL at the database level.
alter table advertisements
  add constraint chk_advertisements_target_url check (target_url is null or target_url ~ '^https?://'),
  add constraint chk_advertisements_image_url check (image_url is null or image_url ~ '^https?://');

create index idx_advertisements_partner on advertisements(partner_id);
create index idx_advertisements_banner_size on advertisements(banner_size) where deleted_at is null;

-- ///////////////////////////////////////////////////////////
-- FILE: migrations/0026_football_center.sql
-- ///////////////////////////////////////////////////////////
-- =========================================================
-- 0026 — PHASE 3c: FOOTBALL CENTER (provider-agnostic)
-- No football data provider is hardcoded anywhere in this schema or the
-- application code built on top of it — see lib/football/ for the
-- provider abstraction layer.
-- =========================================================

-- ---------------------------------------------------------------
-- New permission (this is the first genuinely NEW permission key added
-- since the initial 0002 seed — role_permissions must be backfilled
-- explicitly for existing roles rather than relying on the original
-- seed script, which only ran against permissions that existed then).
-- ---------------------------------------------------------------
insert into permissions (key, description) values
  ('football.manage', 'Manage Football Center: data provider settings, featured leagues/matches, videos');

insert into role_permissions (role_id, permission_id)
select r.id, p.id
from roles r, permissions p
where p.key = 'football.manage'
  and r.key in ('super_admin', 'admin', 'content_manager');

-- ---------------------------------------------------------------
-- Provider config lives in site_settings (non-secret: which provider is
-- active, default league/season) — the actual API keys live in
-- api_credentials (Phase 3a's secure, never-publicly-readable table).
-- ---------------------------------------------------------------
insert into site_settings (key, value) values
  ('football_provider', '{"active": null, "default_league_id": "", "default_season": ""}')
on conflict (key) do nothing;

-- ---------------------------------------------------------------
-- FOOTBALL CACHE — generic response cache for whichever provider is
-- active. Lets the Football Center survive a provider outage or rate
-- limit by serving the last-known-good response instead of crashing,
-- and reduces API usage. Server-only (no public RLS policy) — read and
-- written exclusively by lib/football/cache.ts via the service-role client.
-- ---------------------------------------------------------------
create table football_cache (
  id uuid primary key default gen_random_uuid(),
  cache_key text not null unique,   -- e.g. "fixtures:live", "standings:39:2026"
  provider text not null,
  data jsonb not null,
  cached_at timestamptz not null default now(),
  expires_at timestamptz not null
);
create index idx_football_cache_key on football_cache(cache_key);
create index idx_football_cache_expires on football_cache(expires_at);

alter table football_cache enable row level security;
-- Intentionally no policies — server-only via service-role client.

-- ---------------------------------------------------------------
-- FEATURED LEAGUES — lets the admin curate which leagues appear in the
-- Football Center (League Tables selector, homepage) without any league
-- ID ever being hardcoded in application code.
-- ---------------------------------------------------------------
create table featured_leagues (
  id uuid primary key default gen_random_uuid(),
  provider text not null,
  external_league_id text not null,
  name text not null,
  logo_url text,
  country text,
  season text,
  position int not null default 0,
  is_active boolean not null default true,
  created_by uuid references profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, external_league_id)
);
create index idx_featured_leagues_active on featured_leagues(position) where is_active = true;

create trigger trg_featured_leagues_updated_at before update on featured_leagues
  for each row execute function public.set_updated_at();
create trigger trg_audit_featured_leagues
  after insert or update or delete on featured_leagues
  for each row execute function public.audit_trigger();

alter table featured_leagues enable row level security;
create policy "public read active featured_leagues" on featured_leagues
  for select using (is_active = true);
create policy "football.manage full access featured_leagues" on featured_leagues
  for all using (has_permission('football.manage')) with check (has_permission('football.manage'));

-- ---------------------------------------------------------------
-- FEATURED FIXTURES — admin "pins" a specific match (from whichever
-- provider is active) to be highlighted; the live fixture data itself is
-- still fetched/cached from the provider at render time, only the pin +
-- an optional editorial note are stored locally.
-- ---------------------------------------------------------------
create table featured_fixtures (
  id uuid primary key default gen_random_uuid(),
  provider text not null,
  external_fixture_id text not null,
  note text,
  position int not null default 0,
  is_active boolean not null default true,
  created_by uuid references profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, external_fixture_id)
);
create index idx_featured_fixtures_active on featured_fixtures(position) where is_active = true;

create trigger trg_featured_fixtures_updated_at before update on featured_fixtures
  for each row execute function public.set_updated_at();
create trigger trg_audit_featured_fixtures
  after insert or update or delete on featured_fixtures
  for each row execute function public.audit_trigger();

alter table featured_fixtures enable row level security;
create policy "public read active featured_fixtures" on featured_fixtures
  for select using (is_active = true);
create policy "football.manage full access featured_fixtures" on featured_fixtures
  for all using (has_permission('football.manage')) with check (has_permission('football.manage'));

-- ---------------------------------------------------------------
-- FOOTBALL VIDEOS — editorial content, not from any provider API.
-- ---------------------------------------------------------------
create table football_videos (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(title) between 1 and 200),
  video_url text not null check (video_url ~ '^https?://'),
  thumbnail_media_id uuid references media(id) on delete set null,
  description text,
  is_featured boolean not null default false,
  is_active boolean not null default true,
  published_at timestamptz not null default now(),
  created_by uuid references profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);
create index idx_football_videos_active on football_videos(published_at desc) where is_active = true and deleted_at is null;

create trigger trg_football_videos_updated_at before update on football_videos
  for each row execute function public.set_updated_at();
create trigger trg_audit_football_videos
  after insert or update or delete on football_videos
  for each row execute function public.audit_trigger();

alter table football_videos enable row level security;
create policy "public read active football_videos" on football_videos
  for select using (is_active = true and deleted_at is null);
create policy "football.manage full access football_videos" on football_videos
  for all using (has_permission('football.manage')) with check (has_permission('football.manage'));

-- ///////////////////////////////////////////////////////////
-- FILE: migrations/0027_news_cms.sql
-- ///////////////////////////////////////////////////////////
-- =========================================================
-- 0027 — PHASE 3d: NEWS CMS
-- Categories/tags/post_tags already exist from Phase 1 — this migration
-- only adds what was missing: a denormalized cover image URL (same
-- pattern already used for affiliate_partners.logo_url and
-- site_settings.branding, avoids a join on every public page render).
-- =========================================================
alter table posts add column cover_url text;
alter table football_news add column cover_url text;

-- ///////////////////////////////////////////////////////////
-- FILE: migrations/0028_media_library_and_push.sql
-- ///////////////////////////////////////////////////////////
-- =========================================================
-- 0028 — PHASE 4: MEDIA LIBRARY (gallery UI backing) + PUSH NOTIFICATIONS
-- =========================================================

-- media table already exists (Phase 1) with everything the gallery UI
-- needs (file_name, public_url, mime_type, file_size_bytes, uploaded_by,
-- created_at, deleted_at) — no schema change needed there, only a proper
-- browsing/search UI (this phase's app-layer work).

-- ---------------------------------------------------------------
-- PUSH SUBSCRIPTIONS (Web Push)
-- Visitors opt in from the browser; no login required, so there is no
-- "owner" to scope RLS to. The endpoint URL itself is a long, unguessable,
-- unique value issued by the browser's push service — it functions like a
-- bearer token, which is why public insert/delete-by-endpoint is safe.
-- ---------------------------------------------------------------
create table push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  country text,
  created_at timestamptz not null default now(),
  last_used_at timestamptz
);
create index idx_push_subscriptions_created_at on push_subscriptions(created_at desc);

alter table push_subscriptions enable row level security;

-- Any visitor can subscribe (opt-in) or unsubscribe (by their own,
-- unguessable endpoint) — this is the standard Web Push trust model.
create policy "public insert subscription" on push_subscriptions
  for insert with check (true);
create policy "public delete own subscription" on push_subscriptions
  for delete using (true);

-- Only admins with settings.manage may LIST subscriptions (e.g. to show
-- a subscriber count in the admin UI) — the raw endpoint/keys are still
-- sensitive (they allow sending push messages to that specific browser).
create policy "settings.manage read subscriptions" on push_subscriptions
  for select using (has_permission('settings.manage'));

-- ---------------------------------------------------------------
-- PUSH NOTIFICATION LOG (audit trail of what was broadcast, and to how
-- many recipients / how many failed) — distinct from the generic
-- audit_logs table because this tracks a bulk external side-effect, not
-- a single row change.
-- ---------------------------------------------------------------
create table push_notification_log (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  body text not null,
  url text,
  sent_by uuid references profiles(id) on delete set null,
  recipients_count int not null default 0,
  failures_count int not null default 0,
  created_at timestamptz not null default now()
);

alter table push_notification_log enable row level security;
create policy "settings.manage full access push_log" on push_notification_log
  for all using (has_permission('settings.manage')) with check (has_permission('settings.manage'));

-- ///////////////////////////////////////////////////////////
-- FILE: migrations/0029_final_release_hardening.sql
-- ///////////////////////////////////////////////////////////
-- =========================================================
-- 0029 — FINAL RELEASE: audit fixes
-- Found during the Final Release full-project audit. Applied as a new
-- migration rather than editing migration history, per established
-- practice (see 0020's own header for the same rationale).
-- =========================================================

-- ---------------------------------------------------------------
-- FIX 1 — redundant index. `cache_key` already has a UNIQUE constraint
-- (0026), which Postgres backs with its own implicit unique btree index.
-- The separate `idx_football_cache_key` index duplicated it exactly —
-- same column, same order — adding write overhead for zero query benefit.
-- ---------------------------------------------------------------
drop index if exists idx_football_cache_key;

-- Note: login_attempts(ip_address, created_at) was checked during this
-- audit and already has the correct composite index from migration 0022
-- — no fix needed there.

-- ///////////////////////////////////////////////////////////
-- FILE: migrations/0030_live_streaming.sql
-- ///////////////////////////////////////////////////////////
-- =========================================================
-- 0030 — VERSION 1.1.0: LIVE STREAMING SYSTEM
-- No streaming provider is hardcoded. Providers are entirely
-- admin-defined data (name, base API URL, credentials) consumed by ONE
-- generic, configurable adapter (lib/streaming/) — see
-- LIVE_STREAMING_ARCHITECTURE.md for why this differs from the Football
-- Data provider design (Phase 3c had 3 REAL, documented APIs to adapt to;
-- no such public "official sports streaming API" exists to model against,
-- so the architecture stays provider-shape-agnostic by design).
-- =========================================================

-- ---------------------------------------------------------------
-- New permission (backfilled to existing roles — see 0026 for why this
-- backfill pattern is necessary rather than relying on the original seed).
-- ---------------------------------------------------------------
insert into permissions (key, description) values
  ('streaming.manage', 'Manage live streaming providers and match stream assignments');

insert into role_permissions (role_id, permission_id)
select r.id, p.id
from roles r, permissions p
where p.key = 'streaming.manage'
  and r.key in ('super_admin', 'admin', 'content_manager');

-- ---------------------------------------------------------------
-- STREAMING PROVIDERS
-- Credentials (api_credentials.key = 'streaming:{provider.id}:api_key' /
-- '...:api_secret') are stored ENCRYPTED (lib/security/encryption.ts,
-- AES-256-GCM) — this table itself never holds the key/secret value,
-- only connection status/metadata.
-- ---------------------------------------------------------------
create table streaming_providers (
  id uuid primary key default gen_random_uuid(),
  key text not null unique,     -- slug, e.g. 'provider-a' — used to build the credential keys
  name text not null check (char_length(name) between 1 and 100),
  base_api_url text not null check (base_api_url ~ '^https?://'),
  priority int not null default 0,
  is_active boolean not null default true,
  connection_status text not null default 'unknown' check (connection_status in ('unknown', 'connected', 'error')),
  last_sync_at timestamptz,
  last_error text,
  created_by uuid references profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);
create index idx_streaming_providers_active on streaming_providers(priority) where is_active = true and deleted_at is null;

create trigger trg_streaming_providers_updated_at before update on streaming_providers
  for each row execute function public.set_updated_at();
create trigger trg_audit_streaming_providers
  after insert or update or delete on streaming_providers
  for each row execute function public.audit_trigger();

alter table streaming_providers enable row level security;
create policy "streaming.manage full access providers" on streaming_providers
  for all using (has_permission('streaming.manage')) with check (has_permission('streaming.manage'));
-- Intentionally NO public policy — base_api_url and connection metadata
-- are not needed by the public site directly. The public site learns
-- only "is a stream available + provider display name" via the
-- /api/streaming/* routes (service-role, selecting only safe columns).

-- ---------------------------------------------------------------
-- MATCH STREAMS
-- Assigns one or more streaming providers to a specific match. The match
-- itself is identified by (football_provider, external_fixture_id) —
-- i.e. whichever Football Data provider (Phase 3c) the fixture ID
-- belongs to — exactly like featured_fixtures (Phase 3c) already does,
-- for the same reason: fixture IDs are only unique within their own
-- provider's ID space.
-- ---------------------------------------------------------------
create table match_streams (
  id uuid primary key default gen_random_uuid(),
  football_provider text not null,
  external_fixture_id text not null,
  streaming_provider_id uuid not null references streaming_providers(id) on delete cascade,
  external_stream_id text,   -- the streaming provider's own identifier for this stream, if different from the fixture id
  is_primary boolean not null default false,
  is_active boolean not null default true,
  starts_at timestamptz,
  ends_at timestamptz,
  created_by uuid references profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (football_provider, external_fixture_id, streaming_provider_id)
);
create index idx_match_streams_fixture on match_streams(football_provider, external_fixture_id) where is_active = true;
create index idx_match_streams_provider on match_streams(streaming_provider_id);

create trigger trg_match_streams_updated_at before update on match_streams
  for each row execute function public.set_updated_at();
create trigger trg_audit_match_streams
  after insert or update or delete on match_streams
  for each row execute function public.audit_trigger();

alter table match_streams enable row level security;
create policy "streaming.manage full access match_streams" on match_streams
  for all using (has_permission('streaming.manage')) with check (has_permission('streaming.manage'));
-- No public policy — the public site reaches this only through
-- /api/streaming/* (service-role), which returns availability + provider
-- name only, never raw rows.

-- ---------------------------------------------------------------
-- STREAMING CONNECTION LOGS (Test Connection results + sync history —
-- the "Error Logs" admin panel requirement).
-- ---------------------------------------------------------------
create table streaming_connection_logs (
  id uuid primary key default gen_random_uuid(),
  provider_id uuid references streaming_providers(id) on delete cascade,
  event_type text not null check (event_type in ('test_connection', 'sync')),
  success boolean not null,
  message text,
  created_at timestamptz not null default now()
);
create index idx_streaming_connection_logs_provider on streaming_connection_logs(provider_id, created_at desc);

alter table streaming_connection_logs enable row level security;
create policy "streaming.manage read connection_logs" on streaming_connection_logs
  for select using (has_permission('streaming.manage'));
-- No insert/update/delete policy for anyone — only the server-side test
-- connection / sync routes (service-role) write here.

-- ///////////////////////////////////////////////////////////
-- FILE: migrations/0031_donation_system.sql
-- ///////////////////////////////////////////////////////////
-- =========================================================
-- 0031 — VERSION 1.2.0: DONATION & SUPPORT SYSTEM
-- Gateway credentials use the same encryption module as Live Streaming
-- (v1.1.0, lib/security/encryption.ts) — no separate security system
-- built for this feature. Crypto wallet addresses are NOT secret (donors
-- must see them to send funds), so they live in plain columns here.
-- =========================================================

insert into permissions (key, description) values
  ('donations.manage', 'Manage payment methods, view donations, export reports');

insert into role_permissions (role_id, permission_id)
select r.id, p.id
from roles r, permissions p
where p.key = 'donations.manage'
  and r.key in ('super_admin', 'admin', 'content_manager');

-- ---------------------------------------------------------------
-- PAYMENT METHODS
-- One table for both payment gateways (Stripe/PayPal/future) and crypto
-- wallets (USDT/BTC/ETH/SOL/future) via `method_type`. Gateway API
-- credentials are NEVER stored here — they live encrypted in
-- api_credentials (keyed 'donation:{payment_method.id}:api_key' etc,
-- same pattern as Live Streaming). Crypto wallet_address is public
-- information by nature (donors must see it), so it's a plain column.
-- ---------------------------------------------------------------
create table payment_methods (
  id uuid primary key default gen_random_uuid(),
  key text not null unique,
  name text not null check (char_length(name) between 1 and 100),
  method_type text not null check (method_type in ('gateway', 'crypto')),

  -- gateway-only fields
  provider_key text check (provider_key in ('stripe', 'paypal', 'generic')),
  base_api_url text,       -- only used when provider_key = 'generic' (Stripe/PayPal have fixed, well-known API hosts)

  -- crypto-only fields
  crypto_symbol text,      -- e.g. 'USDT', 'BTC', 'ETH', 'SOL'
  network text,            -- e.g. 'TRC20', 'ERC20', 'Mainnet'
  wallet_address text,

  display_order int not null default 0,
  is_active boolean not null default true,
  created_by uuid references profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,

  constraint chk_payment_method_shape check (
    (method_type = 'gateway' and provider_key is not null and wallet_address is null)
    or
    (method_type = 'crypto' and wallet_address is not null and provider_key is null)
  )
);
create index idx_payment_methods_active on payment_methods(display_order) where is_active = true and deleted_at is null;

create trigger trg_payment_methods_updated_at before update on payment_methods
  for each row execute function public.set_updated_at();
create trigger trg_audit_payment_methods
  after insert or update or delete on payment_methods
  for each row execute function public.audit_trigger();

alter table payment_methods enable row level security;
-- Public read is safe: no secrets live in this table (gateway keys are
-- elsewhere; wallet addresses are meant to be public).
create policy "public read active payment_methods" on payment_methods
  for select using (is_active = true and deleted_at is null);
create policy "donations.manage full access payment_methods" on payment_methods
  for all using (has_permission('donations.manage')) with check (has_permission('donations.manage'));

-- ---------------------------------------------------------------
-- DONATIONS
-- Fully server-mediated: no public RLS policy at all (not even insert).
-- All creation goes through /api/donations/* route handlers (service-role)
-- so amount limits, message length, and provider dispatch are enforced
-- in exactly one place — see DONATION_SYSTEM.md.
-- ---------------------------------------------------------------
create table donations (
  id uuid primary key default gen_random_uuid(),
  payment_method_id uuid references payment_methods(id) on delete set null,
  amount numeric(12, 2) not null check (amount > 0 and amount <= 1000000),
  currency text not null default 'USD' check (currency in ('USD', 'EUR', 'UZS')),
  donor_name text check (donor_name is null or char_length(donor_name) <= 80),
  donor_email text,
  message text check (message is null or char_length(message) <= 500),
  is_anonymous boolean not null default false,
  is_public boolean not null default true,
  status text not null default 'pending' check (status in ('pending', 'completed', 'failed', 'refunded')),
  external_transaction_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index idx_donations_status on donations(status);
create index idx_donations_public_completed on donations(created_at desc) where status = 'completed' and is_public = true and is_anonymous = false;
create index idx_donations_created_at_brin on donations using brin (created_at);

create trigger trg_donations_updated_at before update on donations
  for each row execute function public.set_updated_at();
create trigger trg_audit_donations
  after insert or update or delete on donations
  for each row execute function public.audit_trigger();

alter table donations enable row level security;
create policy "donations.manage full access donations" on donations
  for all using (has_permission('donations.manage')) with check (has_permission('donations.manage'));
-- No public policy whatsoever — see header note.

-- ---------------------------------------------------------------
-- DONATION WEBHOOK LOG (webhook verification audit trail — every
-- inbound webhook, verified or not, is recorded so a rejected/forged
-- attempt is visible to admins, not silently dropped).
-- ---------------------------------------------------------------
create table donation_webhook_log (
  id uuid primary key default gen_random_uuid(),
  payment_method_id uuid references payment_methods(id) on delete set null,
  verified boolean not null,
  event_type text,
  donation_id uuid references donations(id) on delete set null,
  raw_payload jsonb,
  created_at timestamptz not null default now()
);
create index idx_donation_webhook_log_method on donation_webhook_log(payment_method_id, created_at desc);

alter table donation_webhook_log enable row level security;
create policy "donations.manage read webhook_log" on donation_webhook_log
  for select using (has_permission('donations.manage'));
-- No insert/update/delete policy for anyone — only the webhook route
-- (service-role) writes here.

-- ///////////////////////////////////////////////////////////
-- FILE: migrations/0032_v1_3_0_hardening.sql
-- ///////////////////////////////////////////////////////////
-- =========================================================
-- 0032 — VERSION 1.3.0: PRODUCTION INTEGRATION & VERIFICATION
-- Found during full-system rate-limiting review: several genuinely
-- public write endpoints (view-count tracking, promo-code usage
-- tracking, push subscribe/unsubscribe) had no abuse protection at all.
-- Low severity (cosmetic metrics / opt-in noise, not financial or data
-- risk), but still real gaps — see PRODUCTION_READINESS_REPORT.md.
-- =========================================================

-- Generic, reusable rate-limit ledger — server-only (no RLS policies),
-- written exclusively via lib/security/rateLimit.ts. A single shared
-- table instead of a bespoke one per feature (login/streaming/donations
-- already had their own domain-table-based counters before this
-- version and are intentionally left as-is to avoid touching
-- already-verified code — see PRODUCTION_READINESS_REPORT.md).
create table rate_limit_events (
  id uuid primary key default gen_random_uuid(),
  bucket text not null,
  created_at timestamptz not null default now()
);
create index idx_rate_limit_events_bucket on rate_limit_events(bucket, created_at desc);
-- Old entries are cheap to accumulate (small rows, short lookback
-- windows) but a scheduled cleanup is straightforward to add later via
-- the existing Vercel Cron (vercel.json) if the table grows large.

alter table rate_limit_events enable row level security;
-- Intentionally no policies — server-only via service-role client.

